/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication19;

import javax.swing.JOptionPane;

/**
 *
 * @author A R F T
 */
public class Edit extends javax.swing.JFrame {
 public String id;
 Employee obj=new Employee();
    /**
     * Creates new form Edit
     */
    public Edit(String i) {
        initComponents();
        this.id=i;
        
    }
    public Edit()
    {
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nl = new javax.swing.JLabel();
        cl = new javax.swing.JLabel();
        el = new javax.swing.JLabel();
        ntf = new javax.swing.JTextField();
        etf = new javax.swing.JTextField();
        ctf = new javax.swing.JTextField();
        edit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(48, 67, 48));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 199, 77), 2, true));

        nl.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        nl.setForeground(new java.awt.Color(241, 199, 77));
        nl.setText("Name:");

        cl.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        cl.setForeground(new java.awt.Color(241, 199, 77));
        cl.setText("Contact:");

        el.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        el.setForeground(new java.awt.Color(241, 199, 77));
        el.setText("Email:");

        edit.setBackground(new java.awt.Color(125, 36, 34));
        edit.setFont(new java.awt.Font("Viner Hand ITC", 0, 20)); // NOI18N
        edit.setForeground(new java.awt.Color(242, 220, 182));
        edit.setText("Edit");
        edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(213, 172, 53), 2));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cl)
                    .addComponent(el)
                    .addComponent(nl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ntf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nl)
                    .addComponent(ntf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(el)
                    .addComponent(etf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl)
                    .addComponent(ctf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        String n=ntf.getText();
        String e=etf.getText();
        String c=ctf.getText();
        //System.out.print(n +" i am new name");
        obj.setName(n);
        obj.setContact(c);
        obj.setEmail(e);
        //System.out.println(obj.getName());
       // System.out.println(obj.getContact());
        //Admin a= new Admin();
        //boolean f=a.editEmploy(id, obj);
        boolean f=false;
       Employee g = new Employee();
       
        for(int i=0;i<Registered.employees.size();i++)
        {
            g= Registered.employees.get(i);
            System.out.println(g.getId());
            if(g.getId().equals(id))
            {
                obj.setID(id);
                Registered.employees.set(i, obj);
                f=true;
                break;
            }
        }
        if(f)
        {
            JOptionPane.showMessageDialog(null,"Succesful");
            this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Unsucessful");
            this.setVisible(false);
        }
    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cl;
    private javax.swing.JTextField ctf;
    private javax.swing.JButton edit;
    private javax.swing.JLabel el;
    private javax.swing.JTextField etf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nl;
    private javax.swing.JTextField ntf;
    // End of variables declaration//GEN-END:variables
}
