/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication19;

/**
 *
 * @author A R F T
 */
public class Panel3 extends javax.swing.JPanel {

    /**
     * Creates new form Panel3
     */
    public Panel3() {
        initComponents();
        at.setVisible(false);
        ms.setVisible(false);
        il.setVisible(false);
        isi.setVisible(false);
        itf.setVisible(false);
        add.setVisible(false);
        sp3.setVisible(false);
        tb1.setVisible(false);
        ql.setVisible(false);
        qtf.setVisible(false);
        reports.setVisible(false);
        sp1.setVisible(false);
        sp2.setVisible(false);
        vl.setVisible(false);
        vtf.setVisible(false);
        // End of variables declaration              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        il = new javax.swing.JLabel();
        ql = new javax.swing.JLabel();
        vl = new javax.swing.JLabel();
        itf = new javax.swing.JTextField();
        qtf = new javax.swing.JTextField();
        vtf = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        sp2 = new javax.swing.JScrollPane();
        reports = new javax.swing.JTable();
        sp3 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        sp1 = new javax.swing.JScrollPane();
        isi = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        issitem = new javax.swing.JButton();
        mngInv = new javax.swing.JButton();
        at = new javax.swing.JButton();
        ms = new javax.swing.JButton();
        rps = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        il.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        il.setForeground(new java.awt.Color(255, 255, 255));
        il.setText("Item:");
        jPanel2.add(il);
        il.setBounds(189, 220, 50, 22);

        ql.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ql.setForeground(new java.awt.Color(255, 255, 255));
        ql.setText("Quantity:");
        jPanel2.add(ql);
        ql.setBounds(170, 270, 80, 22);

        vl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vl.setForeground(new java.awt.Color(255, 255, 255));
        vl.setText("Vendor:");
        jPanel2.add(vl);
        vl.setBounds(180, 330, 70, 22);

        itf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itfActionPerformed(evt);
            }
        });
        jPanel2.add(itf);
        itf.setBounds(260, 210, 160, 26);
        jPanel2.add(qtf);
        qtf.setBounds(260, 270, 160, 26);
        jPanel2.add(vtf);
        vtf.setBounds(260, 330, 160, 26);

        add.setBackground(new java.awt.Color(26, 37, 84));
        add.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        add.setForeground(new java.awt.Color(198, 203, 209));
        add.setText("ADD");
        add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(add);
        add.setBounds(273, 409, 110, 40);

        reports.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        reports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp ID", "Name", "Quantity"
            }
        ));
        reports.setRowHeight(40);
        reports.setRowMargin(2);
        reports.setSelectionForeground(new java.awt.Color(223, 240, 254));
        sp2.setViewportView(reports);

        jPanel2.add(sp2);
        sp2.setBounds(10, 70, 630, 402);

        tb1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tb1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item", "Quantity", "Vendor", "Action"
            }
        ));
        tb1.setRowHeight(40);
        tb1.setRowMargin(2);
        tb1.setSelectionForeground(new java.awt.Color(223, 240, 254));
        sp3.setViewportView(tb1);

        jPanel2.add(sp3);
        sp3.setBounds(10, 70, 630, 402);

        isi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Emp ID", "Name", "Request", "Quantity", "Action"
            }
        ));
        isi.setRowHeight(45);
        sp1.setViewportView(isi);

        jPanel2.add(sp1);
        sp1.setBounds(10, 70, 630, 380);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\A R F T\\Documents\\GitHub\\GitHub\\JavaApplication19\\images\\Lawrencium.jpg")); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 640, 660);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 640, 660));

        jPanel1.setLayout(null);

        icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\A R F T\\Documents\\GitHub\\GitHub\\JavaApplication19\\images\\manager_100px.png")); // NOI18N
        jPanel1.add(icon);
        icon.setBounds(70, 50, 120, 130);

        issitem.setBackground(new java.awt.Color(26, 37, 84));
        issitem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        issitem.setForeground(new java.awt.Color(171, 175, 245));
        issitem.setText("Issue item");
        issitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issitemActionPerformed(evt);
            }
        });
        jPanel1.add(issitem);
        issitem.setBounds(0, 201, 260, 31);

        mngInv.setBackground(new java.awt.Color(26, 37, 84));
        mngInv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mngInv.setForeground(new java.awt.Color(171, 175, 245));
        mngInv.setText("Manage Inventory");
        mngInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngInvActionPerformed(evt);
            }
        });
        jPanel1.add(mngInv);
        mngInv.setBounds(0, 320, 260, 31);

        at.setBackground(new java.awt.Color(26, 37, 84));
        at.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        at.setForeground(new java.awt.Color(171, 175, 245));
        at.setText("Add item");
        at.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atActionPerformed(evt);
            }
        });
        jPanel1.add(at);
        at.setBounds(0, 380, 260, 31);

        ms.setBackground(new java.awt.Color(26, 37, 84));
        ms.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ms.setForeground(new java.awt.Color(171, 175, 245));
        ms.setText("Manage Stock");
        ms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msActionPerformed(evt);
            }
        });
        jPanel1.add(ms);
        ms.setBounds(0, 440, 260, 31);

        rps.setBackground(new java.awt.Color(26, 37, 84));
        rps.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rps.setForeground(new java.awt.Color(171, 175, 245));
        rps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "View Issued items", "View Returned items", "View Not Returned", "View out of stock" }));
        rps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpsActionPerformed(evt);
            }
        });
        jPanel1.add(rps);
        rps.setBounds(0, 260, 260, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\A R F T\\Documents\\GitHub\\GitHub\\JavaApplication19\\images\\What lies Beyond.jpg")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 260, 660);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void rpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpsActionPerformed
        // TODO add your handling code here:
        sp2.setVisible(true);
        reports.setVisible(true);

        at.setVisible(false);
        ms.setVisible(false);
        il.setVisible(false);
        itf.setVisible(false);
        add.setVisible(false);
        ql.setVisible(false);
        qtf.setVisible(false);
        sp1.setVisible(false);
        vl.setVisible(false);
        vtf.setVisible(false);
        isi.setVisible(false);
        sp3.setVisible(false);
        tb1.setVisible(false);


    }//GEN-LAST:event_rpsActionPerformed

    private void mngInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngInvActionPerformed
        // TODO add your handling code here:
        at.setVisible(false);
        ms.setVisible(false);
        il.setVisible(false);
        itf.setVisible(false);
        add.setVisible(false);

        ql.setVisible(false);
        qtf.setVisible(false);

        sp1.setVisible(false);
        sp2.setVisible(false);
        vl.setVisible(false);
        vtf.setVisible(false);
        isi.setVisible(false);
        sp3.setVisible(false);
        tb1.setVisible(false);

        reports.setVisible(false);

        at.setVisible(true);
        ms.setVisible(true);
    }//GEN-LAST:event_mngInvActionPerformed

    private void itfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itfActionPerformed

    private void issitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issitemActionPerformed
        // TODO add your handling code here:
        sp1.setVisible(true);
        isi.setVisible(true);

        sp3.setVisible(false);
        tb1.setVisible(false);
        at.setVisible(false);
        ms.setVisible(false);
        il.setVisible(false);
        itf.setVisible(false);
        add.setVisible(false);
        ql.setVisible(false);
        qtf.setVisible(false);
        reports.setVisible(false);
        sp2.setVisible(false);
        vl.setVisible(false);
        vtf.setVisible(false);


    }//GEN-LAST:event_issitemActionPerformed

    private void atActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atActionPerformed
        // TODO add your handling code here:

        tb1.setVisible(false);
        sp3.setVisible(false);

        icon.setVisible(false);
        sp1.setVisible(false);
        sp2.setVisible(false);
        isi.setVisible(false);
        reports.setVisible(false);
        ql.setVisible(true);
        qtf.setVisible(true);
        il.setVisible(true);
        itf.setVisible(true);
        vl.setVisible(true);
        vtf.setVisible(true);
        add.setVisible(true);
    }//GEN-LAST:event_atActionPerformed

    private void msActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msActionPerformed
        // TODO add your handling code here:
        sp3.setVisible(true);
//        tb1.setVisible(true);

        il.setVisible(false);
        itf.setVisible(false);
        add.setVisible(false);
        ql.setVisible(false);
        qtf.setVisible(false);
        sp1.setVisible(false);
        sp2.setVisible(false);
        vl.setVisible(false);
        vtf.setVisible(false);
        isi.setVisible(false);
        reports.setVisible(false);
    }//GEN-LAST:event_msActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton at;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel il;
    private javax.swing.JTable isi;
    private javax.swing.JButton issitem;
    private javax.swing.JTextField itf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mngInv;
    private javax.swing.JButton ms;
    private javax.swing.JLabel ql;
    private javax.swing.JTextField qtf;
    private javax.swing.JTable reports;
    private javax.swing.JComboBox<String> rps;
    private javax.swing.JScrollPane sp1;
    private javax.swing.JScrollPane sp2;
    private javax.swing.JScrollPane sp3;
    private javax.swing.JTable tb1;
    private javax.swing.JLabel vl;
    private javax.swing.JTextField vtf;
    // End of variables declaration//GEN-END:variables
}
