/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication19;

import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A R F T
 */
public class Panel3 extends javax.swing.JPanel {

    /**
     * Creates new form Panel3
     */
    public Panel3() {
        initComponents();
        hide();
        // End of variables declaration              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ct = new javax.swing.JLabel();
        ql = new javax.swing.JLabel();
        vl = new javax.swing.JLabel();
        vl2 = new javax.swing.JLabel();
        vl1 = new javax.swing.JLabel();
        ctf = new javax.swing.JTextField();
        itf1 = new javax.swing.JTextField();
        qtf = new javax.swing.JTextField();
        vtf = new javax.swing.JTextField();
        vtf1 = new javax.swing.JTextField();
        qtf1 = new javax.swing.JTextField();
        ql1 = new javax.swing.JLabel();
        il1 = new javax.swing.JLabel();
        vtf2 = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        sp2 = new javax.swing.JScrollPane();
        reports = new javax.swing.JTable();
        sp3 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        sp1 = new javax.swing.JScrollPane();
        isi = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        issitem = new javax.swing.JButton();
        mngInv = new javax.swing.JButton();
        at = new javax.swing.JButton();
        ms = new javax.swing.JButton();
        rps = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        ct.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ct.setForeground(new java.awt.Color(255, 255, 255));
        ct.setText("Category:");
        jPanel2.add(ct);
        ct.setBounds(160, 490, 80, 22);

        ql.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ql.setForeground(new java.awt.Color(255, 255, 255));
        ql.setText("Quantity:");
        jPanel2.add(ql);
        ql.setBounds(170, 270, 80, 22);

        vl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vl.setForeground(new java.awt.Color(255, 255, 255));
        vl.setText("Vendor Email:");
        jPanel2.add(vl);
        vl.setBounds(120, 440, 130, 22);

        vl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vl2.setForeground(new java.awt.Color(255, 255, 255));
        vl2.setText("Vendor Contact:");
        jPanel2.add(vl2);
        vl2.setBounds(120, 390, 130, 22);

        vl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vl1.setForeground(new java.awt.Color(255, 255, 255));
        vl1.setText("Vendor:");
        jPanel2.add(vl1);
        vl1.setBounds(180, 330, 70, 22);

        ctf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctfActionPerformed(evt);
            }
        });
        jPanel2.add(ctf);
        ctf.setBounds(260, 490, 160, 26);

        itf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itf1ActionPerformed(evt);
            }
        });
        jPanel2.add(itf1);
        itf1.setBounds(260, 210, 160, 26);
        jPanel2.add(qtf);
        qtf.setBounds(260, 270, 160, 26);
        jPanel2.add(vtf);
        vtf.setBounds(260, 440, 160, 26);
        jPanel2.add(vtf1);
        vtf1.setBounds(260, 330, 160, 26);
        jPanel2.add(qtf1);
        qtf1.setBounds(260, 490, 160, 26);

        ql1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ql1.setForeground(new java.awt.Color(255, 255, 255));
        ql1.setText("Quantity:");
        jPanel2.add(ql1);
        ql1.setBounds(160, 490, 80, 22);

        il1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        il1.setForeground(new java.awt.Color(255, 255, 255));
        il1.setText("Item:");
        jPanel2.add(il1);
        il1.setBounds(189, 220, 50, 22);
        jPanel2.add(vtf2);
        vtf2.setBounds(260, 390, 160, 26);

        add.setBackground(new java.awt.Color(26, 37, 84));
        add.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        add.setForeground(new java.awt.Color(198, 203, 209));
        add.setText("ADD");
        add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add);
        add.setBounds(280, 530, 110, 40);

        reports.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        reports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp ID", "Name", "Quantity"
            }
        ));
        reports.setRowHeight(40);
        reports.setRowMargin(2);
        reports.setSelectionForeground(new java.awt.Color(223, 240, 254));
        reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsMouseClicked(evt);
            }
        });
        sp2.setViewportView(reports);

        jPanel2.add(sp2);
        sp2.setBounds(10, 70, 630, 402);

        tb1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tb1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item", "Quantity", "Vendor", "Action"
            }
        ));
        tb1.setRowHeight(40);
        tb1.setRowMargin(2);
        tb1.setSelectionForeground(new java.awt.Color(223, 240, 254));
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        sp3.setViewportView(tb1);

        jPanel2.add(sp3);
        sp3.setBounds(10, 70, 630, 402);

        isi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Emp ID", "Name", "Request", "Quantity", "Action"
            }
        ));
        isi.setRowHeight(45);
        sp1.setViewportView(isi);

        jPanel2.add(sp1);
        sp1.setBounds(10, 70, 630, 380);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\A R F T\\Documents\\GitHub\\GitHub\\JavaApplication19\\images\\Lawrencium.jpg")); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 640, 660);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 640, 660));

        jPanel1.setLayout(null);

        icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\A R F T\\Documents\\GitHub\\GitHub\\JavaApplication19\\images\\manager_100px.png")); // NOI18N
        jPanel1.add(icon);
        icon.setBounds(70, 50, 120, 130);

        issitem.setBackground(new java.awt.Color(26, 37, 84));
        issitem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        issitem.setForeground(new java.awt.Color(171, 175, 245));
        issitem.setText("Issue item");
        issitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issitemActionPerformed(evt);
            }
        });
        jPanel1.add(issitem);
        issitem.setBounds(0, 201, 260, 31);

        mngInv.setBackground(new java.awt.Color(26, 37, 84));
        mngInv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mngInv.setForeground(new java.awt.Color(171, 175, 245));
        mngInv.setText("Manage Inventory");
        mngInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngInvActionPerformed(evt);
            }
        });
        jPanel1.add(mngInv);
        mngInv.setBounds(0, 320, 260, 31);

        at.setBackground(new java.awt.Color(26, 37, 84));
        at.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        at.setForeground(new java.awt.Color(171, 175, 245));
        at.setText("Add item");
        at.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atActionPerformed(evt);
            }
        });
        jPanel1.add(at);
        at.setBounds(0, 380, 260, 31);

        ms.setBackground(new java.awt.Color(26, 37, 84));
        ms.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ms.setForeground(new java.awt.Color(171, 175, 245));
        ms.setText("Manage Stock");
        ms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msActionPerformed(evt);
            }
        });
        jPanel1.add(ms);
        ms.setBounds(0, 440, 260, 31);

        rps.setBackground(new java.awt.Color(26, 37, 84));
        rps.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rps.setForeground(new java.awt.Color(171, 175, 245));
        rps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "View Issued items", "View Returned items", "View Not Returned", "View out of stock" }));
        rps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpsActionPerformed(evt);
            }
        });
        jPanel1.add(rps);
        rps.setBounds(0, 260, 260, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\A R F T\\Documents\\GitHub\\GitHub\\JavaApplication19\\images\\What lies Beyond.jpg")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 260, 660);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void rpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpsActionPerformed
        // TODO add your handling code here:
        hide();
        sp2.setVisible(true);
        reports.setVisible(true);

    }//GEN-LAST:event_rpsActionPerformed

    private void mngInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngInvActionPerformed
        // TODO add your handling code here:
        hide();

        at.setVisible(true);
        ms.setVisible(true);
    }//GEN-LAST:event_mngInvActionPerformed

    private void ctfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctfActionPerformed

    private void issitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issitemActionPerformed
        // TODO add your handling code here:
        hide();
        sp1.setVisible(true);
        isi.setVisible(true);


    }//GEN-LAST:event_issitemActionPerformed

    private void atActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atActionPerformed
        // TODO add your handling code here:

        hide();

        ql.setVisible(true);
        qtf.setVisible(true);
        ct.setVisible(true);
        ctf.setVisible(true);
        vl.setVisible(true);
        vtf.setVisible(true);
        vl1.setVisible(true);
        vtf1.setVisible(true);
        vl2.setVisible(true);
        vtf2.setVisible(true);
        itf1.setVisible(true);
        il1.setVisible(true);
        add.setVisible(true);
    }//GEN-LAST:event_atActionPerformed

    private void msActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msActionPerformed
        // TODO add your handling code here:
        hide();
        sp3.setVisible(true);
        tb1.setVisible(true);
        qtf1.setVisible(true);
        ql1.setVisible(true);

        model = (DefaultTableModel) tb1.getModel();
        model.setRowCount(0);
        Object[] rowData = new Object[4];
        System.out.println(Registered.stock.size());
        for (int i = 0; i < Registered.stock.size(); i++) {
            rowData[0] = Registered.stock.get(i).getName();
            rowData[1] = Registered.stock.get(i).getQuantity();
            rowData[2] = Registered.stock.get(i).getSuppliername();
            rowData[3] = "YDRGZM";
            model.addRow(rowData);
        }
        tb1.getSelectedRow();
        /* StockTableModel t = new StockTableModel(Registered.stock);
        
        tb1.setModel(t);
        
        Action increase = new AbstractAction() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
                JTable table = (JTable) e.getSource();
                int row = Integer.valueOf(e.getActionCommand());
                StockTableModel model = (StockTableModel) table.getModel();
                model.editRow(row);                
            }
        };
        ButtonColumn inc = new ButtonColumn(tb1, increase, 4);
        
        Action deleteAction = new AbstractAction() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
                JTable table = (JTable) e.getSource();
                int row = Integer.valueOf(e.getActionCommand());
                StockTableModel model = (StockTableModel) table.getModel();
                model.deleteRow(row);                
            }
        };
        ButtonColumn deleteButton = new ButtonColumn(tb1, deleteAction, 5);*/
    }//GEN-LAST:event_msActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        Item i = new Item();
        String c = ctf.getText();
        int q = Integer.parseInt(qtf.getText());
        String ve = vtf.getText();
        String vn = vtf1.getText();
        String vc = vtf2.getText();
        String t = itf1.getText();
        i.setItem(t, q, vn, vc, ve, c, i);
        Registered.stock.add(i);
    }//GEN-LAST:event_addActionPerformed

    private void itf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itf1ActionPerformed

    private void reportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_reportsMouseClicked

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        // TODO add your handling code here:
        int r = tb1.getSelectedRow();
        if (r > -1) {
            //System.out.println("" + Registered.stock.get(r).getQuantity());
            qtf1.setText("" + Registered.stock.get(r).getQuantity());
        } else {
            qtf1.setText("Not found");
        }
    }//GEN-LAST:event_tb1MouseClicked

    public void addRowData() {
        DefaultTableModel model = (DefaultTableModel) reports.getModel();
        Object rowData[] = new Object[3];
        for (int i = 0; i < Registered.employees.size(); i++) {
            rowData[0] = Registered.employees.get(i).getName();
        }
    }

    public void hide() {
        at.setVisible(false);
        ms.setVisible(false);
        ct.setVisible(false);
        isi.setVisible(false);
        ctf.setVisible(false);
        add.setVisible(false);
        sp3.setVisible(false);
        tb1.setVisible(false);
        ql.setVisible(false);
        qtf.setVisible(false);
        reports.setVisible(false);
        sp1.setVisible(false);
        sp2.setVisible(false);
        vl.setVisible(false);
        vtf.setVisible(false);
        vl1.setVisible(false);
        vl2.setVisible(false);
        vtf1.setVisible(false);
        vtf2.setVisible(false);
        itf1.setVisible(false);
        il1.setVisible(false);
        qtf1.setVisible(false);
        ql1.setVisible(false);
    }
    DefaultTableModel model;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton at;
    private javax.swing.JLabel ct;
    private javax.swing.JTextField ctf;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel il1;
    private javax.swing.JTable isi;
    private javax.swing.JButton issitem;
    private javax.swing.JTextField itf1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mngInv;
    private javax.swing.JButton ms;
    private javax.swing.JLabel ql;
    private javax.swing.JLabel ql1;
    private javax.swing.JTextField qtf;
    private javax.swing.JTextField qtf1;
    private javax.swing.JTable reports;
    private javax.swing.JComboBox<String> rps;
    private javax.swing.JScrollPane sp1;
    private javax.swing.JScrollPane sp2;
    private javax.swing.JScrollPane sp3;
    private javax.swing.JTable tb1;
    private javax.swing.JLabel vl;
    private javax.swing.JLabel vl1;
    private javax.swing.JLabel vl2;
    private javax.swing.JTextField vtf;
    private javax.swing.JTextField vtf1;
    private javax.swing.JTextField vtf2;
    // End of variables declaration//GEN-END:variables
}
