/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication19;

/**
 *
 * @author A R F T
 */
public class Panel2 extends javax.swing.JPanel {

    String item;
    String action;
    /**
     * Creates new form Panel2
     */
    public Panel2(String c, String Action) {
        initComponents();
        this.item=c;
        this.action=Action;
        
        jTable1.setVisible(false);
        jScrollPane1.setVisible(false);
        jTable2.setVisible(false);
        jScrollPane2.setVisible(false);
        req.setVisible(false);
        it.setVisible(false);
        itm.setVisible(false);
        wnt.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        wnt = new javax.swing.JLabel();
        req = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        it = new javax.swing.JLabel();
        itm = new javax.swing.JTextField();
        itm1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Quan = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(140, 150, 215));
        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\A R F T\\Documents\\GitHub\\GitHub\\JavaApplication19\\images\\worker_128px.png")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 30, 120, 130);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Employee");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 180, 90, 23);

        jButton1.setBackground(new java.awt.Color(223, 240, 254));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\A R F T\\Documents\\GitHub\\GitHub\\JavaApplication19\\images\\repository_40px.png")); // NOI18N
        jButton1.setText("Make Request");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 250, 230, 50);

        jButton2.setBackground(new java.awt.Color(223, 240, 254));
        jButton2.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\A R F T\\Documents\\GitHub\\GitHub\\JavaApplication19\\images\\left_40px.png")); // NOI18N
        jButton2.setText("Return item");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 330, 230, 40);

        jButton3.setBackground(new java.awt.Color(223, 240, 254));
        jButton3.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jButton3.setText("Back");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jButton3);
        jButton3.setBounds(50, 510, 130, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\A R F T\\Documents\\GitHub\\GitHub\\JavaApplication19\\images\\Kye Meh.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 250, 660);

        add(jPanel1);
        jPanel1.setBounds(-1, -1, 250, 740);

        jPanel2.setBackground(new java.awt.Color(186, 224, 189));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wnt.setBackground(new java.awt.Color(204, 204, 204));
        wnt.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        wnt.setForeground(new java.awt.Color(66, 169, 157));
        wnt.setText("Want something not in list ?");
        jPanel2.add(wnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        req.setBackground(new java.awt.Color(66, 169, 157));
        req.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        req.setText("Request");
        req.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        req.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqActionPerformed(evt);
            }
        });
        jPanel2.add(req, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 90, -1));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        it.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        it.setForeground(new java.awt.Color(66, 169, 157));
        it.setText("Item:");
        jPanel2.add(it, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        itm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmActionPerformed(evt);
            }
        });
        jPanel2.add(itm, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 70, -1));

        itm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm1ActionPerformed(evt);
            }
        });
        jPanel2.add(itm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 190, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Action"
            }
        ));
        jTable1.setToolTipText("Chose item and click Request button");
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(2);
        jTable1.setSelectionForeground(new java.awt.Color(223, 240, 254));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employ ID", "Item", "Action"
            }
        ));
        jTable2.setRowHeight(40);
        jTable2.setRowMargin(2);
        jTable2.setSelectionForeground(new java.awt.Color(223, 240, 254));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, -1));

        Quan.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        Quan.setForeground(new java.awt.Color(66, 169, 157));
        Quan.setText("Quantity:");
        jPanel2.add(Quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, -1, -1));

        add(jPanel2);
        jPanel2.setBounds(250, 0, 650, 660);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTable2.setVisible(false);
        jScrollPane2.setVisible(false);
        jTable1.setVisible(true);
        jScrollPane1.setVisible(true);
        req.setVisible(true);
        it.setVisible(true);
        itm.setVisible(true);
        wnt.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void itmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTable2.setVisible(true);
        jScrollPane2.setVisible(true);
        jTable1.setVisible(false);
        jScrollPane1.setVisible(false);
        req.setVisible(false);
        it.setVisible(false);
        itm.setVisible(false);
        wnt.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void reqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqActionPerformed
        // TODO add your handling code here:
        Employee e= new Employee();
        Request i= new Request();
        
        String item =itm1.getText();
        int q= Integer.parseInt(itm.getText());
       i.setName(item);
       i.setQuant(q);
       e.addRequest(i);
        
    }//GEN-LAST:event_reqActionPerformed

    private void itm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itm1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Quan;
    private javax.swing.JLabel it;
    private javax.swing.JTextField itm;
    private javax.swing.JTextField itm1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton req;
    private javax.swing.JLabel wnt;
    // End of variables declaration//GEN-END:variables
}
