/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication19;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A R F T
 */
public class Panel2 extends javax.swing.JPanel {
Employee obj=new Employee();
    String item;
    int index;
    /**
     * Creates new form Panel2
     */
    public Panel2() {
        initComponents();
  for(int i=0;i<Registered.employees.size();i++)
  {
      obj= Registered.employees.get(i);
      if(obj.getId().equals(Login.emp))
      {
          break;
      }
  }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        req = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        it = new javax.swing.JLabel();
        itm = new javax.swing.JTextField();
        retrn = new javax.swing.JButton();
        itm1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Quan = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(140, 150, 215));
        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\A R F T\\Documents\\GitHub\\GitHub\\JavaApplication19\\images\\worker_128px.png")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 30, 120, 130);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Employee");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 180, 90, 23);

        jButton1.setBackground(new java.awt.Color(223, 240, 254));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\A R F T\\Documents\\GitHub\\GitHub\\JavaApplication19\\images\\repository_40px.png")); // NOI18N
        jButton1.setText("Make Request");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 250, 230, 50);

        jButton2.setBackground(new java.awt.Color(223, 240, 254));
        jButton2.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\A R F T\\Documents\\GitHub\\GitHub\\JavaApplication19\\images\\left_40px.png")); // NOI18N
        jButton2.setText("Return item");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 330, 230, 40);

        close.setBackground(new java.awt.Color(223, 240, 254));
        close.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        close.setText("Close");
        close.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(50, 490, 130, 40);

        jButton3.setBackground(new java.awt.Color(223, 240, 254));
        jButton3.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jButton3.setText("Back");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(50, 420, 130, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\A R F T\\Documents\\GitHub\\GitHub\\JavaApplication19\\images\\Kye Meh.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 250, 660);

        add(jPanel1);
        jPanel1.setBounds(-1, -1, 250, 740);

        jPanel2.setBackground(new java.awt.Color(186, 224, 189));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        req.setBackground(new java.awt.Color(66, 169, 157));
        req.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        req.setText("Request");
        req.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        req.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqActionPerformed(evt);
            }
        });
        jPanel2.add(req, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, 90, -1));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        it.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        it.setForeground(new java.awt.Color(66, 169, 157));
        it.setText("Item:");
        jPanel2.add(it, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        itm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmActionPerformed(evt);
            }
        });
        jPanel2.add(itm, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 70, -1));

        retrn.setBackground(new java.awt.Color(66, 169, 157));
        retrn.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        retrn.setText("Return");
        retrn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        retrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrnActionPerformed(evt);
            }
        });
        jPanel2.add(retrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, 90, -1));

        itm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm1ActionPerformed(evt);
            }
        });
        jPanel2.add(itm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 190, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity"
            }
        ));
        jTable1.setToolTipText("Chose item and click Request button");
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(2);
        jTable1.setSelectionForeground(new java.awt.Color(223, 240, 254));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Category", "Status"
            }
        ));
        jTable2.setRowHeight(40);
        jTable2.setRowMargin(2);
        jTable2.setSelectionForeground(new java.awt.Color(223, 240, 254));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, -1));

        Quan.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        Quan.setForeground(new java.awt.Color(66, 169, 157));
        Quan.setText("Quantity:");
        jPanel2.add(Quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, -1, -1));

        add(jPanel2);
        jPanel2.setBounds(250, 0, 650, 660);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        hide();
        jTable1.setVisible(true);
        jScrollPane1.setVisible(true);
        req.setVisible(true);
        it.setVisible(true);
        itm.setVisible(true);
        Quan.setVisible(true);
        itm1.setVisible(true);
        model = (DefaultTableModel) jTable1.getModel();
        
        Object[] rowData = new Object[2];
        //System.out.println(Registered.employees.size());
        for (int i = 0; i < Registered.stock.size(); i++) {
            rowData[0] = Registered.stock.get(i).getName();
            rowData[1] = Registered.stock.get(i).getQuantity();
            model.addRow(rowData);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void itmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        hide();
        jTable2.setVisible(true);
        jScrollPane2.setVisible(true);
        it.setVisible(true);
        itm.setVisible(true);
        itm1.setVisible(true);
        retrn.setVisible(true);
        Quan.setVisible(true);
        model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        Object[] rowData = new Object[3];
        //System.out.println(Registered.employees.size());
        for (int i = 0; i < obj.issued.size(); i++) {
            rowData[0] = obj.issued.get(i).getName();
            rowData[1] = obj.issued.get(i).getCategory();
             rowData[2] = obj.issued.get(i).status;
            model.addRow(rowData);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void reqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqActionPerformed
        // TODO add your handling code here:        
        Request i= new Request();
        itm1.setEditable(false);
        String item =itm1.getText();
        int q= Integer.parseInt(itm.getText());
       i.setName(item);
       i.setQuant(q);
       boolean f=obj.addRequest(i);
        if(f)
            JOptionPane.showMessageDialog(null,"Success");
        else
            JOptionPane.showMessageDialog(null,"Failure");
    }//GEN-LAST:event_reqActionPerformed

    private void itm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itm1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int n= jTable1.getSelectedRow();
        if(n>-1)
        {
            this.index=n;
            itm1.setText(Registered.stock.get(n).getName());
            
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void retrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrnActionPerformed
        // TODO add your handling code here:
        obj.issued.get(index).status="Returned";
        JOptionPane.showMessageDialog(null,"Success");
    }//GEN-LAST:event_retrnActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int n= jTable2.getSelectedRow();
        if(n>-1)
        {
            this.index=n;
            String name= obj.issued.get(n).getName();
           int qu = obj.issued.get(n).getQuantity();
            String s=obj.issued.get(n).status;
            itm1.setText(name);
            itm.setText(qu +"");
        }
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Driver.hidden();
        this.setVisible(false);
        Login l= new Login();
        l.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
       
        Registered.saveApproved();
        Registered.saveStock();
        Registered.saveEmploy();
        Registered.saveIssued();
         try {
                finalize();
            } catch (Throwable ex) {
                Logger.getLogger(Panel2.class.getName()).log(Level.SEVERE, null, ex);
            }
         this.setVisible(false);
          JOptionPane.showMessageDialog(null,"Thank you for using program");
    }//GEN-LAST:event_closeActionPerformed
public void hide()
{
        jTable1.setVisible(false);
        jScrollPane1.setVisible(false);
        jTable2.setVisible(false);
        jScrollPane2.setVisible(false);
        req.setVisible(false);
        it.setVisible(false);
        itm.setVisible(false);   
        retrn.setVisible(false);
}
DefaultTableModel model;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Quan;
    private javax.swing.JButton close;
    private javax.swing.JLabel it;
    private javax.swing.JTextField itm;
    private javax.swing.JTextField itm1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton req;
    private javax.swing.JButton retrn;
    // End of variables declaration//GEN-END:variables
}
