/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication19;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.File;
import java.io.IOException;
import java.sql.Timestamp;
/**
 *
 * @author A R F T
 */
public class Table2 extends javax.swing.JFrame {
public String it;
public int index;
public Employee obj= new Employee();
public Item t= new Item();
public Issued_item s= new Issued_item();
    /**
     * Creates new form Table2
     */
    public Table2(String d,int i) {
        initComponents();
        
    }
    public Table2()
    {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        item = new javax.swing.JLabel();
        itf = new javax.swing.JTextField();
        qntf = new javax.swing.JTextField();
        quan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(125, 36, 34));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(244, 175, 38)));

        jTable1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(244, 175, 38)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity"
            }
        ));
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(2);
        jTable1.setSelectionForeground(new java.awt.Color(223, 240, 254));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(48, 67, 48));
        jButton1.setForeground(new java.awt.Color(244, 175, 38));
        jButton1.setText("Issue");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 175, 38), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        item.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        item.setForeground(new java.awt.Color(244, 175, 38));
        item.setText("Item:");

        quan.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        quan.setForeground(new java.awt.Color(244, 175, 38));
        quan.setText("Quantity:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(item, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(quan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qntf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item)
                    .addComponent(itf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quan)
                    .addComponent(qntf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model;
        obj= Registered.employees.get(index);
      model= (DefaultTableModel) jTable1.getModel();
        Object[] rowData = new Object[2];
        for(int j=0;j<obj.requests.size();j++)
        {
           rowData[0]= obj.requests.get(j).getName();
           rowData[1]= obj.requests.get(j).getQuant();
           model.addRow(rowData);
        }
       
        int n= jTable1.getSelectedRow();
        if(n>-1)
        {
            this.index=n;
            this.it= obj.requests.get(n).getName();
            int q=obj.requests.get(n).getQuant();
            itf.setText(it);
            qntf.setText(q +"");
            t.setName(it);
            t.setQuantity(q);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String j=itf.getText();
        int n= Integer.parseInt(qntf.getText());
        Inventory st= new Inventory();
        int e=st.itemExist(j);
         int k= Integer.parseInt(qntf.getText());
        if(e>=0)
        {
            t.setCategory(Registered.stock.get(e).getCategory());
            boolean f=t.setSupplier(Registered.stock.get(e).getSuppliername(), Registered.stock.get(e).getSupplier().getEmail(), Registered.stock.get(e).getSupplier().getContact(), t);
             f=s.setIssued(t);
             s.id=obj.getId();
             f=obj.addIssue(s);
            f= generateReceipt();
            Registered.stock.get(e).setQuantity(Registered.stock.get(e).getQuantity()-n);
            if(f)
            {
                JOptionPane.showMessageDialog(null,"Success");
                this.setVisible(false);
            }
             else
            {
                 JOptionPane.showMessageDialog(null,"Unsuccess");
                 this.setVisible(false);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Out of stock");
        }
         
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table2().setVisible(true);
            }
        });
    }
public boolean generateReceipt()
    {
       
      boolean flag=false;
       try 
      {
      File myObj = new File("Record.txt");
      }
       catch (Exception ex) 
      {
      System.out.println("An error occurred.");
      ex.printStackTrace(); 
      return false;
       }
      try
      {
      FileWriter myfile=new FileWriter("Receipt.txt");
  
      
      myfile.write("Name :"+ obj.getName()+ "\n");
      myfile.write("ID :" +obj.getId() +"\n");
      myfile.write("Contact:"+ obj.getContact()+ "\n");
      myfile.write("Email :"+ obj.getEmail()+"\n");
      myfile.write("Issued item :" + s.getName()+"\n");
      myfile.write("Quantity :" + s.getQuantity()+"\n");
      myfile.write("Category :"+s.getCategory()+"\n");
      myfile.write("Time ;" +getTime()+ "\n");
      flag=true;
      myfile.flush();
      myfile.close();
      }
      catch(IOException e )
    {
        System.out.println("Exception ocurred");
      e.printStackTrace(); 
      return false;
    }
    return flag;
    }
     public String getTime()
       {
         String t;
         Timestamp time;
         time = new Timestamp(System.currentTimeMillis());
         t= time.toString();
         return t;
       }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel item;
    private javax.swing.JTextField itf;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField qntf;
    private javax.swing.JLabel quan;
    // End of variables declaration//GEN-END:variables
}
